/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Inc/stm/digital/Gpio.h"
#include "../Inc/stm/sys/Rcc.h"
#include "../Inc/stm/analog/Dac.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    volatile stm32::system::RccRegisters* rcc = reinterpret_cast<stm32::system::RccRegisters*>(0X4002'1000);

    stm32::digital::gpio::Gpio gpioA(0x4800'0000);
    stm32::digital::gpio::GpioPinConfiguration outputPinConfig{};
    stm32::digital::gpio::GpioPinConfiguration dacPinConfig(stm32::digital::gpio::PinMode::Analog);

    stm32::analog::dac::Dac dac1(0x5000'0800);
    stm32::analog::dac::DacChannelConfiguration dac1configuration = {};

    rcc->AHB2ENR |= 0x1;
    rcc->AHB2ENR |= 0x1 << 16;
    asm("nop; nop; nop");
    gpioA.configureGpio(0, outputPinConfig);
    gpioA.configureGpio(4, dacPinConfig);
    gpioA.writeGpio(0, true);

    dac1.disable(stm32::analog::dac::Channel::Channel1);
    dac1.configure(dac1configuration, stm32::analog::dac::Channel::Channel1);
    dac1.setOutputValue(
        stm32::analog::dac::Dac::voltageToValue(1652, stm32::analog::dac::DataResolution::TwelveBit),
        stm32::analog::dac::Channel::Channel1
        );
    dac1.enable(stm32::analog::dac::Channel::Channel1);


    /* Loop forever */
	for(;;);

}
