/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <cstdint>

#include "../Inc/stm/digital/Gpio.h"
#include "../Inc/stm/sys/Rcc.h"
#include "../Inc/stm/analog/Dac.h"
#include "../Inc/stm/analog/Adc.h"
#include "../Inc/stm/sys/Dma.h"
#include "../Inc/stm/sys/GeneralPurposeTim.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint16_t adc_buffer[16];

int main()
{
    using namespace stm32;

    volatile system::RccRegisters* rcc = reinterpret_cast<system::RccRegisters*>(0X4002'1000);

    digital::gpio::Gpio gpioA(0x4800'0000);

    rcc->AHB2ENR |= 0x1; //gpio a
    rcc->AHB2ENR |= 0x1 << 16; //dac 1
    rcc->CCIPR &= ~(0b11 << 28);
    rcc->CCIPR |= 0b10 << 28; //adc 1 clock selection
    rcc->AHB2ENR |= 0x1 << 13; //adc 1
    rcc->AHB1ENR |= 0x1; //dma 1
    rcc->AHB1ENR |= 0x1 << 2; //dmamux
    rcc->APB1ENR1 |= 0x1; //tim 2
    asm("nop; nop; nop");

    digital::gpio::GpioPinConfiguration outputConfig = digital::gpio::GpioPinConfiguration();
    digital::gpio::GpioPinConfiguration inputConfig = digital::gpio::GpioPinConfiguration(digital::gpio::PinMode::Input);
    gpioA.configureGpio(digital::gpio::Pin::PIN_0, outputConfig);
    gpioA.configureGpio(digital::gpio::Pin::PIN_1, outputConfig);
    gpioA.configureGpio(digital::gpio::Pin::PIN_2, outputConfig);
    gpioA.configureGpio(digital::gpio::Pin::PIN_3, inputConfig);

    uint8_t color = 0;

    for (;;) {
        if (gpioA.readGpio(digital::gpio::Pin::PIN_3))
            color = (color == 2) ? 0 : (color += 1);
        switch (color) {
            case 0:
                gpioA.writeGpio(digital::gpio::Pin::PIN_0);
                gpioA.writeGpio(digital::gpio::Pin::PIN_2, false);
                break;
            case 1:
                gpioA.writeGpio(digital::gpio::Pin::PIN_1);
                gpioA.writeGpio(digital::gpio::Pin::PIN_0, false);
                break;
            case 2:
                gpioA.writeGpio(digital::gpio::Pin::PIN_2);
                gpioA.writeGpio(digital::gpio::Pin::PIN_1, false);
                break;
            default:
                break;
        }

    }

}
