/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "../Inc/stm/digital/Gpio.h"
#include "../Inc/stm/sys/Rcc.h"
#include "../Inc/stm/analog/Dac.h"
#include "../Inc/stm/analog/Adc.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    using namespace stm32;

    volatile system::RccRegisters* rcc = reinterpret_cast<system::RccRegisters*>(0X4002'1000);

    digital::gpio::Gpio gpioA(0x4800'0000);
    digital::gpio::GpioPinConfiguration outputPinConfig{};
    digital::gpio::GpioPinConfiguration dacPinConfig(digital::gpio::PinMode::Analog);

    analog::dac::Dac dac1(0x5000'0800);
    analog::dac::DacChannelConfiguration dac1configuration = {};

    analog::adc::Adc adc1(0x5000'0000);

    rcc->AHB2ENR |= 0x1;
    rcc->AHB2ENR |= 0x1 << 16;
    rcc->AHB2ENR |= 0x1 << 13;
    asm("nop; nop; nop");

    gpioA.configureGpio(0, dacPinConfig);
    gpioA.configureGpio(4, dacPinConfig);

    dac1.disable(analog::dac::Channel::Channel1);
    dac1.configure(dac1configuration, analog::dac::Channel::Channel1);
    dac1.setOutputValue(
        analog::dac::Dac::voltageToValue(1652, analog::dac::DataResolution::TwelveBit),
        analog::dac::Channel::Channel1
        );
    dac1.enable(analog::dac::Channel::Channel1);

    adc1.disable();
    adc1.setDeepPowerDown(false);
    adc1.setVoltageRegulator(true);
    for (uint32_t i = 10000; i > 0; i--) {}

    adc1.setSamplingTime(analog::adc::AdcSamplingTime::CYCLES_24_5, 1);

    analog::adc::AdcConversionSequence coversionSequence = analog::adc::AdcConversionSequenceBuilder(1).build();
    adc1.setConversionSequence(coversionSequence);

    adc1.enable();
    adc1.startConversion();

    /* Loop forever */
	for(;;) {
		while (!adc1.getStatus().eoconv) {}
		dac1.setOutputValue(
			adc1.getValue(),
			analog::dac::Channel::Channel1
		);
		adc1.startConversion();
	}

}
